name: Build ksud
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Rust
      run: rustup update stable

    - name: Build ksud
      run: cargo build --release --manifest-path ./userspace/ksud/Cargo.toml

    - name: Upload ksud artifact
      uses: actions/upload-artifact@v4
      with:
        name: ksud-x86_64
        path: userspace/ksud/target/release/ksud
